### ISSUE TITLE
Argument 1 passed to PsrHttpFactory::createRequest() must be an instance of Request, null given

### ISSUE THREAD

**Issue by nelson6e65** [paknahad/jsonapi-bundle#87]
Hi. IDK if put this here or in [paknahad/jsonapi-bundle](https://github.com/paknahad/jsonapi-bundle), because this happens when using this extension.

I get this error (when authenticating using NelmioApiDocs or via Postman) when I use a custom Finder or [paknahad/jsonapi-querifier-bundle](https://github.com/paknahad/jsonapi-querifier-bundle):

```
[critical] Uncaught Error: Argument 1 passed to Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory::createRequest() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in ./vendor/paknahad/jsonapi-bundle/src/Factory/JsonApiFactory.php on line 45
```

> When `APP_DEBUG` is set to `true`, this break the JSON response with the warning as plain text, so only works with `APP_DEBUG=false`.

Seems to be related with the requestStack, like an issue in https://github.com/AdactiveSAS/saml2-bridge-bundle/issues/28

https://github.com/paknahad/jsonapi-bundle/blob/98c75e1337f9043aeafcd3dbf032243b7d59abbf/src/Factory/JsonApiFactory.php#L41-L46

https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/a517b096de30416a53d5f7dc3f24a6947e743e2b/src/Entity/HostedEntities.php#L141

**Maybe my config is wrong?**

My `services.yaml` config is:

```yml
services:
  paknahad_json_api.helper_filter.finder:
    class: Paknahad\JsonApiQuerifierBundle\Finder\Querifier
    public: false
    tags:
      - { name: paknahad.json_api.finder }
```

**_Am I missing something?_**
